### ISSUE TITLE
No visitor defined for <refentry>! Skipping.

### ISSUE THREAD

**Issue by htakeda** [asciidoctor/docbookrx#24]
I performed below command.
But it seems to be unaware refentry.
I don't know why this error happened.

```
$ ./bin/docbookrx ./drbd9/drbd.conf.xml 
No visitor defined for <refentry>! Skipping.
```

[drbd.conf.txt](https://github.com/opendevise/docbookrx/files/202051/drbd.conf.txt)

**Comment by mojavelinux** [comment]
refentry is a node that docbookrx does not currently handle. refentry is typically used for a man page. AsciiDoc does have support for the man page structure, so this is something that docbookrx should be able to handle. We should start with a test case with both the DocBook and the expected AsciiDoc, then make the necessary changes to the code to get that test to pass.

**Comment by mojavelinux** [comment]
This would be covered by #23.
