### ISSUE TITLE
Setting up docbookrx on Windows environment giving the issue - 'bundler command not found: docbookrx'

### ISSUE THREAD

**Issue by vishalkrsinha** [asciidoctor/docbookrx#68]
I was trying to setup 'docbookrx' on my Windows environment by following the steps from url: https://github.com/asciidoctor/docbookrx/blob/master/README.adoc

But, I starting getting below error message::
                 bundler: command not found: docbookrx
                 Install missing gem executables with `bundle install`

Screenshot for the reference also attached. 
![docbookrx-windows-setup-issue](https://user-images.githubusercontent.com/42475844/90558517-d2cbea80-e1b9-11ea-997e-02deb8bb95af.png)

**Comment by vishalkrsinha** [comment]
I got it working now by upgrading 'nokogiri' version and updating the same (1.10.10) in docbookrx.gemspec file. 
Please refer the attached screenshots for the solution...

![docbookrx-windows-setup-issue-resolved](https://user-images.githubusercontent.com/42475844/90559305-078c7180-e1bb-11ea-842f-c9445dabb80c.png)


![docbookrx gemspec-version-change](https://user-images.githubusercontent.com/42475844/90559597-6a7e0880-e1bb-11ea-85c2-390d0e0ee744.png)

**Comment by mojavelinux** [comment]
I've updated the dependencies in c8609437fddf1cc83e6241ce8e1d3d8ba2cb4c92. Would you like to test again?

One thing we are not yet doing is testing on Windows. Thus, we cannot yet verify that this gem works on Windows. That would require either setting up a GitHub Action (like https://github.com/asciidoctor/asciidoctor-pdf/blob/master/.github/workflows/ci.yml) or an AppVeyor job (like https://github.com/asciidoctor/asciidoctor/blob/master/.appveyor.yml). We should follow up on that in a separate issue.
